# Generated by Django 4.2 on 2024-01-04 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_about_cv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='cv',
            field=models.FileField(help_text='upload your cv', upload_to='cv'),
        ),
        migrations.AlterField(
            model_name='education',
            name='year',
            field=models.IntegerField(),
        ),
    ]
